baseURL = 'https://rafal-a-bogaczewicz.github.io'
languageCode = 'pl'
title = 'Rafa≈Ç A. Bogaczewicz'

theme = []

[params]
  morska_zielen = "#16a085"
  bio = "Fizyk teoretyk. Specjalista w zakresie metod ab initio i modelowania kwantowego."

[menu]
  [[menu.main]]
    name = "Publikacje"
    url = "/publications/"
    weight = 1
  [[menu.main]]
    name = "Konferencje"
    url = "/conferences/"
    weight = 2

[markup]
  [markup.goldmark.renderer]
    unsafe = true
