baseURL = 'https://rafal-a-bogaczewicz.github.io'
defaultContentLanguage = 'pl'
title = 'Rafał A. Bogaczewicz'

# Budujemy ab initio - brak zewnętrznego motywu
theme = []

[params]
  gorska_zielen = "#4a674f"

[languages]
  [languages.pl]
    languageName = 'PL'
    contentDir = 'content/pl'
    weight = 1
    # Spójne i poprawne językowo bio PL
    bio = "Pasjonat odkrywania świata&nbsp;– zarówno naukowo, jak&nbsp;i podczas wypraw."
    [languages.pl.menu]
      [[languages.pl.menu.main]]
        name = "Publikacje"
        url = "/publications/"
        weight = 1
      [[languages.pl.menu.main]]
        name = "Konferencje"
        url = "/conferences/"
        weight = 2

  [languages.en]
    languageName = 'EN'
    contentDir = 'content/en'
    weight = 2
    # Prestiżowe tłumaczenie American English (High-Value / Action-oriented)
    bio = "Passionate about discovery&nbsp;– both in research and during exploration."
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "Publications"
        url = "/publications/"
        weight = 1
      [[languages.en.menu.main]]
        name = "Conferences"
        url = "/conferences/"
        weight = 2

[markup]
  [markup.goldmark.renderer]
    unsafe = true
