baseURL = 'https://rafal-a-bogaczewicz.github.io'
languageCode = 'pl'
title = 'Rafał A. Bogaczewicz'

# Budujemy ab initio, więc nie potrzebujemy zewnętrznego motywu
theme = []

[params]
  morska_zielen = "#16a085"
  bio = "Fizyk teoretyk. High Value Man. Tradycyjne wartości."

[menu]
  [[menu.main]]
    name = "Publikacje"
    url = "/publications/"
    weight = 1
  [[menu.main]]
    name = "Konferencje"
    url = "/conferences/"
    weight = 2

[markup]
  [markup.goldmark.renderer]
    unsafe = true # Pozwala na wstawianie czystego HTML (np. wzorów lub specyficznego formatowania)
